application: you-google-app-engine-id
version: 1-0
runtime: python
api_version: 1

# The default expires information for static assets
default_expiration: "2d"


handlers:
- url: /static
  static_dir: static
  #secure: always
- url: .*
  script: main.py
  #secure: always